name: Cleanup old branches
on:
  workflow_dispatch: {}

jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubicloud
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.10
        with:
          repo_token: ${{ github.token }}
          date: "1 day ago"
          dry_run: false
          delete_tags: true
          minimum_tags: 5
          extra_protected_branch_regex: ^(main)$
          extra_protected_tag_regex: "^v.*"
          exclude_open_pr_branches: true
